### ISSUE TITLE
【ログイン・サインアップ画面】スタイル変更

### ISSUE THREAD

**Issue by ryota-1231** [miracleave-ltd/mirameetVol28#43]

**Comment by kobayashi-toshihiko** [comment]
## What
- 【ログイン・サインアップ画面】スタイル変更


## Why
- 既存のアプリ画面のスタイルをmirameet用に合わせる為、画面のスタイルを変更

**Comment by kobayashi-toshihiko** [comment]
style.cssにて、【ログイン・サインアップ画面】スタイルを修正
